
name: Run Unit Tests


on:
  
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master


jobs:
  test:
   
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
     
          python-version: '3.x'

     
      - name: Install dependencies
        run: |
          # Met à jour pip (gestionnaire de paquets Python) pour éviter les problèmes de compatibilité.
          python -m pip install --upgrade pip
          # Installe unittest2, une version améliorée de la bibliothèque unittest (bien que unittest soit inclus dans Python).
          pip install unittest2

      - name: Run tests
        run: python -m unittest test_mot.py